apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-appfrontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: appfrontend.plectrum
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-appfrontend
            port:
              number: 8080